[package]
name = "merk"
description = "Merkle key/value store"
version = "1.0.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
time = "0.1.42"
hex = "0.4.2"
colored = "1.8.0"
num_cpus = "1.10.0"
byteorder = "1.3.2"
failure = "0.1.6"
ed = "0.1.6"
blake3 = "0.3.7"

[dependencies.rand]
version = "0.8.3"
features = ["small_rng"]

[dependencies.rocksdb]
git = "https://github.com/rust-rocksdb/rust-rocksdb"
version = "0.16.0"
rev = "v0.16.0"
default-features = false

[dependencies.jemallocator]
version = "0.3.2"
features = ["disable_initial_exec_tls"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "merk"
harness = false

[[bench]]
name = "ops"
harness = false
